# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

from collections.abc import MutableMapping

from ambuild2.frontend.system import System
from ambuild2.frontend.v2_2.cpp.compiler import CliCompiler
from ambuild2.frontend.v2_2.cpp.gcc import GCC, Clang, Emscripten
from ambuild2.frontend.v2_2.cpp.msvc import MSVC
from ambuild2.nodetypes import EnvDataDict
from ambuild2.util import Expando

type _Environ = MutableMapping[str, str]

class CommandAndVendor:
    def __init__(self, argv: list[str], vendor: GCC | Clang | Emscripten | MSVC, arch: str) -> None: ...

class CompilerNotFoundException(Exception):
    def __init__(self, message: str = ...) -> None: ...

kClangTuple: tuple[str, ...]
kGccTuple: tuple[str, ...]
kIntelTuple: tuple[str, ...]
kMsvcTuple: tuple[str, ...]
kGnuArchMap: dict[str, str]

def FindToolsInEnv(env: _Environ, tools: list[str]) -> tuple[dict[str, str], bool]: ...
def AutoDetectCxx(host: System, gen_options: Expando, **kwargs: str) -> CliCompiler: ...
def IsCrossCompile(host: System, target: System) -> bool: ...

class CompilerLocator:
    def __init__(self, host: System, gen_options: Expando, **kwargs: str) -> None: ...
    def detect(self) -> CliCompiler: ...
    def detect_cxx(self) -> CliCompiler: ...
    def detect_from_env(self) -> CliCompiler: ...
    def detect_msvc_tools(self, cli: CliCompiler) -> None: ...
    def detect_gcc_tools(self, cli: CliCompiler) -> None: ...
    def detect_gcc_tool(self, tool_name: str, env_name: str, commands: list[str], check_argv: list[str]) -> list[str]: ...
    def create_cli(self, cc: CommandAndVendor, cxx: CommandAndVendor, env_data: EnvDataDict | None = ...) -> CliCompiler: ...
    def detect_msvc(self) -> CliCompiler: ...
    def try_msvc_bat(self, bat_file: str, pass_arch: bool = ...) -> CliCompiler | None: ...
    def find_default_compiler(self) -> CliCompiler: ...
    def find_compiler(self, mode: str, cmd: str, cc_family: str | None = ...) -> CommandAndVendor | None: ...
    def run_compiler(self, mode: str, cmd: str, assumed_family: str, env: _Environ | None = ..., abs_path: str | None = ...) -> tuple[CommandAndVendor, None] | tuple[None, Exception]: ...
    def verify_compiler(self, flags: list[str], mode: str, cmd: str, assumed_family: str, env: _Environ, abs_path: str) -> CommandAndVendor: ...
