# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

from typing import Literal

from ambuild2.frontend.system import System
from ambuild2.frontend.v2_2.cpp.deptypes import PchNodes
from ambuild2.frontend.v2_2.cpp.vendor import Archiver, Linker, Vendor

class GCCLookalike(Vendor):
    def __init__(self, version: str) -> None: ...
    @property
    def behavior(self) -> Literal['gcc']: ...
    @property
    def definePrefix(self) -> Literal['-D']: ...
    @property
    def objSuffix(self) -> Literal['.o']: ...
    @property
    def debugInfoArgv(self) -> list[str]: ...
    def parseDebugInfoType(self, debuginfo: Literal['separate', 'bundled']) -> str: ...
    @property
    def pch_needs_source_file(self) -> Literal[False]: ...
    def formatInclude(self, build_root: str, output_path: str, include: str) -> list[str]: ...
    @property
    def emits_dependency_file(self) -> Literal[True]: ...
    def dependencyArgv(self, out_file: str) -> list[str]: ...
    def objectArgs(self, sourceFile: str, objFile: str) -> list[str]: ...
    def makePchArgv(self, source_file: str, obj_file: str, source_type: str) -> list[str]: ...
    def programLinkArgv(self, cmd_argv: list[str], files: list[str], linkFlags: list[str], symbolFile: str, outputFile: str) -> list[str]: ...
    def libLinkArgv(self, cmd_argv: list[str], files: list[str], linkFlags: list[str], symbolFile: str, outputFile: str) -> list[str]: ...
    def preprocessArgv(self, sourceFile: str, outFile: str) -> list[str]: ...
    @staticmethod
    def IncludePath(outputPath: str, includePath: str) -> str: ...

class GCC(GCCLookalike):
    def __init__(self, version: str) -> None: ...
    @property
    def name(self) -> Literal['gcc']: ...
    @property
    def family(self) -> Literal['gcc']: ...
    def like(self, name: str) -> bool: ...
    @property
    def pch_needs_strong_deps(self) -> Literal[False]: ...
    def nameForPch(self, source_file: str) -> str: ...
    def formatPchInclude(self, build_root: str, output_path: str, pch: PchNodes) -> list[str]: ...

class Clang(GCCLookalike):
    def __init__(self, version: str, vendor_prefix: str | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def family(self) -> Literal['clang']: ...
    def like(self, name: str) -> bool: ...
    @property
    def debugInfoArgv(self) -> list[str]: ...
    def nameForPch(self, source_file: str) -> str: ...
    def formatPchInclude(self, build_root: str, output_path: str, pch: PchNodes) -> list[str]: ...
    @property
    def pch_needs_strong_deps(self) -> Literal[True]: ...

class Emscripten(Clang):
    def __init__(self, version: str) -> None: ...
    def nameForExecutable(self, name: str, target: System) -> str: ...
    def nameForSharedLibrary(self, name: str, target: System) -> str: ...
    def nameForStaticLibrary(self, name: str, target: System) -> str: ...
    @property
    def name(self) -> Literal['emscripten']: ...
    @property
    def family(self) -> Literal['emscripten']: ...  # type: ignore[override]
    def like(self, name: str) -> bool: ...
    @property
    def debugInfoArgv(self) -> list[str]: ...

class GccLinker(Linker):
    def __init__(self) -> None: ...
    def like(self, name: str) -> bool: ...

class GccArchiver(Archiver):
    def __init__(self) -> None: ...
    def like(self, name: str) -> bool: ...
    def makeArgv(self, base_argv: list[str], files: list[str], outputFile: str) -> list[str]: ...
