# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

from typing import Literal

from ambuild2.frontend.v2_2.cpp.deptypes import PchNodes
from ambuild2.frontend.v2_2.cpp.vendor import Archiver, Linker, Vendor

class MSVC(Vendor):
    def __init__(self, version: str) -> None: ...
    @property
    def name(self) -> Literal['msvc']: ...
    @property
    def behavior(self) -> Literal['msvc']: ...
    @property
    def family(self) -> Literal['msvc']: ...
    def like(self, name: str) -> bool: ...
    @property
    def definePrefix(self) -> Literal['/D']: ...
    @property
    def objSuffix(self) -> Literal['.obj']: ...
    @property
    def debugInfoArgv(self) -> list[str]: ...
    def makePchArgv(self, source_file: str, pch_file: str, source_type: str) -> list[str]: ...
    def parseDebugInfoType(self, debuginfo: Literal['separate', 'bundled']) -> Literal['separate']: ...
    def objectArgs(self, sourceFile: str, objFile: str) -> list[str]: ...
    def programLinkArgv(self, cmd_argv: list[str], files: list[str], linkFlags: list[str], symbolFile: str, outputFile: str) -> list[str]: ...
    def libLinkArgv(self, cmd_argv: list[str], files: list[str], linkFlags: list[str], symbolFile: str, outputFile: str) -> list[str]: ...
    def preprocessArgv(self, sourceFile: str, outFile: str) -> list[str]: ...
    @staticmethod
    def IncludePath(output_path: str, include_path: str) -> str: ...
    def formatInclude(self, build_root: str, output_path: str, include: str) -> list[str]: ...
    def formatPchInclude(self, build_root: str, output_path: str, pch: PchNodes) -> list[str]: ...
    @property
    def shared_pdb_name(self) -> str: ...
    @property
    def pch_needs_strong_deps(self) -> Literal[True]: ...
    @property
    def pch_needs_source_file(self) -> Literal[True]: ...
    @property
    def shared_pdb_flags(self) -> set[str]: ...
    def nameForPch(self, source_file: str) -> str: ...
    @property
    def emits_dependency_file(self) -> Literal[False]: ...

class MsvcLinker(Linker):
    def __init__(self) -> None: ...
    def like(self, name: str) -> bool: ...

class MsvcArchiver(Archiver):
    def __init__(self) -> None: ...
    def like(self, name: str) -> bool: ...
    def makeArgv(self, base_argv: list[str], files: list[str], outputFile: str) -> list[str]: ...
