# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

from abc import abstractmethod
from typing import Literal, Never, Self

from ambuild2.frontend.system import System
from ambuild2.frontend.v2_2.cpp.deptypes import PchNodes
from ambuild2.frontend.version import Version

class Vendor:
    version_string: int | str
    version: Version
    extra_props: dict[str, str]

    def __init__(self, version: str) -> None: ...
    def nameForExecutable(self, name: str, target: System) -> str: ...
    def nameForSharedLibrary(self, name: str, target: System) -> str: ...
    def nameForStaticLibrary(self, name: str, target: System) -> str: ...
    def equals(self, other: Self) -> bool: ...
    @property
    @abstractmethod
    def behavior(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def family(self) -> str: ...
    def like(self, name: str) -> bool: ...
    @property
    @abstractmethod
    def definePrefix(self) -> str: ...
    @property
    @abstractmethod
    def objSuffix(self) -> str: ...
    @property
    def debug_info_argv(self) -> Never: ...  # Never implemented
    @abstractmethod
    def parseDebugInfoType(self, debuginfo: Literal['separate', 'bundled']) -> str: ...
    @abstractmethod
    def formatInclude(self, build_root: str, output_path: str, include: str) -> list[str]: ...
    def formatPchInclude(self, build_root: str, output_path: str, pch: PchNodes) -> list[str]: ...
    @abstractmethod
    def objectArgs(self, sourceFile: str, objFile: str) -> list[str]: ...
    @abstractmethod
    def programLinkArgv(self, cmd_argv: list[str], files: list[str], linkFlags: list[str], symbolFile: str, outputFile: str) -> list[str]: ...
    @abstractmethod
    def libLinkArgv(self, cmd_argv: list[str], files: list[str], linkFlags: list[str], symbolFile: str, outputFile: str) -> list[str]: ...
    def nameForPrecompiledHeader(self, name: str) -> Never: ...
    @property
    @abstractmethod
    def pch_needs_source_file(self) -> bool: ...
    @property
    def shared_pdb_flags(self) -> set[str]: ...
    def nameForPch(self, source_file: str) -> str: ...
    @property
    @abstractmethod
    def emits_dependency_file(self) -> Literal[True, False]: ...
    def dependencyArgv(self, out_file: str) -> list[str]: ...

class Linker:
    def __init__(self) -> None: ...
    @abstractmethod
    def like(self, name: str) -> bool: ...

class Archiver:
    def __init__(self) -> None: ...
    @abstractmethod
    def like(self, name: str) -> bool: ...
