# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

from collections.abc import MutableSequence
from typing import Literal, Self

from _typeshed import Incomplete
from ambuild2.frontend.proxy import AttributeProxy
from ambuild2.frontend.v2_2.context import BuildContext
from ambuild2.frontend.v2_2.context_manager import ContextManager
from ambuild2.frontend.v2_2.cpp import compiler
from ambuild2.frontend.v2_2.cpp.deptypes import CppNodes
from ambuild2.frontend.v2_2.cpp.msvc import MSVC
from ambuild2.frontend.v2_2.cpp.vendor import Linker
from ambuild2.frontend.v2_2.vs.gen import Generator
from ambuild2.frontend.v2_2.vs.nodes import ProjectNode
from ambuild2.frontend.version import Version

def GetProjectFileSuffix(version: Version) -> Literal['.vcxproj', '.vcproj']: ...

class Project:
    ctor_: type[StaticLibrary]
    name: str
    sources: list[str]
    include_hotlist: list[Incomplete]
    builders_: MutableSequence[Library | Program | StaticLibrary]

    def __init__(self, ctor: type[StaticLibrary], name: str) -> None: ...
    def Configure(self, compiler: Compiler, name: str, tag: str) -> None: ...
    def default(self, compiler: Compiler) -> Program | StaticLibrary: ...
    def finish(self, cx: BuildContext) -> None: ...
    def generate(self, generator: Generator, cx: BuildContext) -> list[CppNodes]: ...
    def generate_split(self, generator: Generator, cx: BuildContext) -> list[CppNodes]: ...
    def generate_combined(self, generator: Generator, cx: BuildContext) -> list[CppNodes]: ...
    def export(self, cm: ContextManager, node: ProjectNode) -> None: ...

class VisualStudio(MSVC):
    def __init__(self, version: int) -> None: ...
    def like(self, name: str) -> bool: ...

class VsLinker(Linker):
    def __init__(self) -> None: ...
    def like(self, name: str) -> bool: ...

class Compiler(compiler.Compiler):
    linker: VsLinker  # type: ignore[assignment]

    def __init__(self, vendor: VisualStudio, target_arch: str = ...) -> None: ...
    def clone(self) -> Compiler: ...
    @staticmethod
    def GetVersionFromVS(vs_version: int) -> int: ...
    def Program(self, name: str) -> Program: ...
    def Library(self, name: str) -> Library: ...
    def StaticLibrary(self, name: str) -> Project: ...
    def PrecompiledHeaders(self, name: str, source_type: str) -> PrecompiledHeaders: ...
    def like(self, name: str) -> bool: ...

class BinaryBuilder:
    project_: Project
    compiler: Compiler
    sources: list[str]
    include_hotlist: list[Incomplete]
    name_: str
    tag_: str

    def __init__(self, project: Project, compiler: Compiler, name: str, tag: str) -> None: ...
    @property
    def localFolder(self) -> str: ...
    @property
    def outputFile(self) -> str: ...
    def Module(self, context: AttributeProxy, name: str) -> Self: ...

class Program(BinaryBuilder):
    def __init__(self, project: Project, compiler: Compiler, name: str, tag: str) -> None: ...
    @staticmethod
    def buildOutputName(name: str) -> str: ...
    @property
    def type(self) -> Literal['program']: ...
    @property
    def configurationType(self) -> Literal['Application']: ...

class Library(BinaryBuilder):
    def __init__(self, project: Project, compiler: Compiler, name: str, tag: str) -> None: ...
    @staticmethod
    def buildOutputName(name: str) -> str: ...
    @property
    def type(self) -> Literal['library']: ...
    @property
    def configurationType(self) -> Literal['DynamicLibrary']: ...

class StaticLibrary(BinaryBuilder):
    def __init__(self, project: Project, compiler: Compiler, name: str, tag: str) -> None: ...
    @staticmethod
    def buildOutputName(name: str) -> str: ...
    @property
    def type(self) -> Literal['static']: ...
    @property
    def configurationType(self) -> Literal['StaticLibrary']: ...

class PchNodes:
    name: str
    sources: list[str]

    def __init__(self, name: str, sources: list[str]) -> None: ...

class PrecompiledHeaders(BinaryBuilder):
    compiler: Compiler
    name_: str
    sources: list[str]

    def __init__(self, compiler: Compiler, name: str) -> None: ...
    def finish(self, cx: BuildContext) -> None: ...
    def generate(self, generator: Generator, cx: BuildContext) -> PchNodes: ...
