# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

from typing import Literal, TextIO

from ambuild2.frontend.v2_2.context_manager import ContextManager
from ambuild2.frontend.v2_2.vs.cxx import Library, Program, StaticLibrary
from ambuild2.frontend.v2_2.vs.nodes import ProjectNode
from ambuild2.frontend.vs.xmlbuilder import XmlBuilder

def export(cm: ContextManager, node: ProjectNode) -> None: ...
def export_fp(cm: ContextManager, node: ProjectNode, fp: TextIO) -> None: ...
def export_body(cm: ContextManager, node: ProjectNode, xml: XmlBuilder) -> None: ...
def get_target_platform(builder: Library | StaticLibrary | Program) -> Literal['x64', 'Win32']: ...
def condition_for(builder: Library | StaticLibrary | Program) -> str: ...
def export_configuration_headers(node: ProjectNode, xml: XmlBuilder) -> None: ...
def export_configuration_properties(node: ProjectNode, xml: XmlBuilder) -> None: ...
def export_configuration_user_props(node: ProjectNode, xml: XmlBuilder) -> None: ...
def export_configuration_paths(node: ProjectNode, xml: XmlBuilder) -> None: ...
def sanitize_val_defines(defines: list[str]) -> list[str]: ...
def make_unified_header(builder: Library | StaticLibrary | Program, name: str, sources: list[str]) -> None: ...
def export_configuration_options(node: ProjectNode, xml: XmlBuilder, builder: Library | StaticLibrary | Program) -> None: ...
def export_source_files(node: ProjectNode, xml: XmlBuilder) -> None: ...
