# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

import sqlite3
from collections.abc import Callable, Mapping
from types import TracebackType
from typing import Any, Literal, Self

from ambuild2.nodetypes import DirtyState, Entry, EnvDataTuple, NodeType, ToolsEnv

type _IsolationLevel = Literal['DEFERRED', 'EXCLUSIVE', 'IMMEDIATE'] | None
type _NodeRowData = tuple[NodeType, float, int, str | None, Entry | int | None, bytes | None, int | None]

def CreateDatabase(path: str) -> Database: ...

class Database:
    path: str
    cn: sqlite3.Connection | None
    node_cache_: dict[int, Entry]
    path_cache_: dict[str, Entry]
    env_cache_: dict[int, ToolsEnv]
    env_reverse_lookup_: dict[EnvDataTuple, ToolsEnv]

    def __init__(self, path: str) -> None: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None) -> None: ...
    def commit(self) -> None: ...
    def flush_caches(self) -> None: ...
    def check_upgrade(self) -> None: ...
    def upgrade_to_v2(self) -> Literal[2]: ...
    def upgrade_to_v3(self) -> Literal[3]: ...
    def upgrade_to_v4(self) -> Literal[4]: ...
    def upgrade_to_v5(self) -> Literal[5]: ...
    def upgrade_to_v6(self) -> Literal[6]: ...
    def query_var(self, var: str) -> str | None: ...
    def set_var(self, var: str, value: str) -> None: ...
    def add_folder(self, parent: Entry, path: str) -> Entry: ...
    def add_output(self, folder_entry: Entry, path: str, kind: NodeType = ...) -> Entry: ...
    def find_or_add_source(self, path: str) -> Entry: ...
    def add_source(self, path: str) -> Entry: ...
    def add_file(self, type: NodeType, path: str, folder_entry: Entry | None = ...) -> Entry: ...
    def update_command(self, entry: Entry, type: NodeType, folder: Entry | str, data: Mapping[str, Any], dirty: DirtyState, refactoring: bool, env_data: EnvDataTuple) -> bool: ...
    def add_command(self, type: NodeType, folder: Entry | str, data: Mapping[str, Any], dirty: DirtyState, env_data: EnvDataTuple) -> Entry: ...
    def add_weak_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def add_strong_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def add_dynamic_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def add_shared_output_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def drop_dynamic_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def drop_weak_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def drop_strong_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def drop_shared_output_edge(self, from_entry: Entry, to_entry: Entry) -> None: ...
    def query_node(self, id: int) -> Entry: ...
    def query_path(self, path: str) -> Entry | None: ...
    def import_node(self, id: int, row: _NodeRowData) -> Entry: ...
    def query_strong_outgoing(self, node: Entry) -> set[Entry]: ...
    def query_shared_outputs(self, node: Entry) -> set[Entry]: ...
    def query_outgoing(self, node: Entry) -> set[Entry]: ...
    def query_weak_inputs(self, node: Entry) -> set[Entry]: ...
    def query_strong_inputs(self, node: Entry) -> set[Entry]: ...
    def query_command_of(self, node: Entry) -> None: ...
    def query_shared_commands_of(self, node: Entry) -> list[Entry]: ...
    def query_dynamic_inputs(self, node: Entry) -> set[Entry]: ...
    def fetch_environment(self, env_id: int) -> ToolsEnv: ...
    def add_environment(self, env_data: EnvDataTuple) -> ToolsEnv: ...
    def mark_dirty(self, entry: Entry) -> None: ...
    def unmark_dirty(self, entry: Entry, stamp: float | None = ...) -> None: ...
    def set_dirty_type(self, entry: Entry, dirtyType: DirtyState) -> None: ...
    def query_mkdir(self, aggregate: Callable[[Entry], None]) -> None: ...
    def query_known_dirty(self, aggregate: Callable[[Entry], None]) -> None: ...
    def query_maybe_dirty(self, aggregate: Callable[[Entry], None]) -> None: ...
    def query_commands(self, aggregate: Callable[[Entry], None]) -> None: ...
    def load_environments(self) -> None: ...
    def drop_links(self, entry: Entry) -> None: ...
    def drop_entry(self, entry: Entry) -> None: ...
    def drop_folder(self, entry: Entry) -> None: ...
    def drop_source(self, output: Entry) -> None: ...
    def drop_output(self, output: Entry) -> None: ...
    def drop_command(self, cmd_entry: Entry) -> None: ...
    def add_or_update_script(self, path: str) -> None: ...
    def query_scripts(self, aggregate: Callable[[int, str, float], None]) -> None: ...
    def query_dead_sources(self, aggregate: Callable[[Entry], None]) -> None: ...
    def query_dead_shared_outputs(self, aggregate: Callable[[Entry], None]) -> None: ...
    def drop_script(self, path: str) -> None: ...
    def drop_unused_environments(self) -> None: ...
    def change_to_folder(self, entry: Entry) -> None: ...
    def change_to_output(self, entry: Entry, kind: NodeType) -> None: ...
    def vacuum(self) -> None: ...
    def printGraph(self) -> None: ...
    def printGraphNode(self, node: Entry, indent: int) -> None: ...

class IsolationChange:
    def __init__(self, cn: sqlite3.Connection, level: _IsolationLevel) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None) -> None: ...
