# vim: set ts=8 sts=2 sw=2 tw=99 et:

# Source nodes are files that are leaf inputs to the build system, and are not
# generated as part of the build process.
Source = 'src'

# Command nodes have associated data in the command table, and produce some
# kind of output.
Command = 'cmd'

# Output nodes are files that have been generated as a result of a command.
Output = 'out'

# Mkdir nodes represent a folder creation action, either explicit or
# automatically generated.
Mkdir = 'mkd'

# Copy nodes represent a file copy, from a source to a destination. They do
# not have a command counterpart.
Copy = 'cp'

# FolderCopy nodes snapshot the contents of a folder - non-recursively - and
# become dirty when files are added or removed. They automatically maintain
# individual copy links for each file in the folder.
#
# To ensure proper ordering, any files in the folder that are dependent on a
# build action, will have their copy node properly depending on that action.
Folder = 'cpa'

# Link nodes represent a symlink, from a source to a destination. They do
# not have a command counterpart. On operating systems where symlinking is not
# available or unreliable, copies may be performed instead.
Symlink = 'ln'

# C++ nodes are a builtin type that are capable of performing post-processing
# on the result of the command (for example, for dependency computation). They
# are used when using AMBuild2's automated C++ builders.
Cxx = 'cxx'

# The basic properties of a node as it exists in the database.
def Node(object):
  def __init__(self, id, type, path, folder, stamp, dirty, generated):
    # Unique node ID (integer)
    self.id = id

    # Node type, from above.
    self.type = type

    # Either an absolute path for a source node, or a relative path for an
    # output node.
    self.path = path

    # For non-source nodes, this is a link to a 'Mkdir' node describing its
    # working directory.
    self.folder = folder

    # Last modification time.
    self.stamp = stamp

    # Whether or not we've remembered this node as dirty.
    self.dirty = dirty

    # 1 if the node was automatically generated by the build process, 0
    # otherwise.
    self.generated = generated
