# vim: set ts=8 sts=4 sw=4 tw=99 et:
#
# This file is part of AMBuild.
#
# AMBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option any later version.
#
# AMBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMBuild. If not, see <http://www.gnu.org/licenses/>.

import re
from collections.abc import Callable, Mapping, MutableMapping, Sequence
from subprocess import Popen
import sys
from types import TracebackType
from typing import Any, BinaryIO, Final, Literal, TextIO, TypeIs

import ambuild2.frontend.vs.nodes as vs
from _typeshed import Incomplete
from ambuild2.nodetypes import Entry

# os._Environ
type _Environ = MutableMapping[str, str]
type NormalizedArch = Literal['x86', 'x86_64', 'arm', 'arm64', 'unknown']
type _PLATFORMS = Literal['windows', 'mac', 'linux', 'freebsd', 'openbsd', 'netbsd', 'solaris', 'cygwin', 'unknown']

INSTALLED_BY_PIP_OR_SETUPTOOLS: Literal[True]

def NormalizeArchString(arch: str) -> NormalizedArch | str: ...
def DecodeArchString(arch: str) -> tuple[str, str]: ...

ALL_PLATFORMS: list[Literal['windows', 'mac', 'linux', 'freebsd', 'openbsd', 'netbsd', 'solaris', 'cygwin']] = ...

def Platform() -> _PLATFORMS: ...
def DetectHostAbi() -> Literal['', 'unknown', 'gnueabihf', 'gnueabi']: ...
def DetectHostArmAbi() -> Literal['', 'unknown', 'gnueabihf', 'gnueabi']: ...
def IsLinux() -> bool: ...
def IsFreeBSD() -> bool: ...
def IsNetBSD() -> bool: ...
def IsOpenBSD() -> bool: ...
def IsWindows() -> bool: ...
def IsCygwin() -> bool: ...
def IsMac() -> bool: ...
def IsSolaris() -> bool: ...
def IsUnixy() -> bool: ...
def IsBSD() -> bool: ...

ExecutableSuffix: Literal['', '.exe'] = ...
SharedLibSuffix: Literal['.dll', '.dylib', '.so'] = ...
StaticLibSuffix: Literal['.a', '.lib'] = ...
StaticLibPrefix: Literal['', 'lib'] = ...

def ExecutableSuffixForPlatform(platform: str) -> Literal['', '.exe']: ...
def SharedLibSuffixForPlatform(platform: str) -> Literal['.dll', '.dylib', '.so']: ...
def StaticLibSuffixForPlatform(platform: str) -> Literal['.lib', '.a']: ...
def StaticLibPrefixForPlatform(platform: str) -> Literal['', 'lib']: ...

type _PE_FILE_MACHINE_TYPES = Literal[0, 0x014C, 0x01C4, 0x8664, 0xAA64]

if sys.platform == 'win32':
    class WinAPI:
        IMAGE_FILE_MACHINE_UNKNOWN: Literal[0]
        IMAGE_FILE_MACHINE_I386: Literal[0x014C]
        IMAGE_FILE_MACHINE_ARMNT: Literal[0x01C4]
        IMAGE_FILE_MACHINE_AMD64: Literal[0x8664]
        IMAGE_FILE_MACHINE_ARM64: Literal[0xAA64]

        @staticmethod
        def bidict(kv_pairs: list[tuple[_PE_FILE_MACHINE_TYPES, NormalizedArch]]) -> dict[NormalizedArch | _PE_FILE_MACHINE_TYPES, _PE_FILE_MACHINE_TYPES | NormalizedArch]: ...

        kMachineTypes: dict[NormalizedArch | _PE_FILE_MACHINE_TYPES, _PE_FILE_MACHINE_TYPES | NormalizedArch]
        class MachineAttributes:
            Unset: Literal[0]
            UserEnabled: Literal[0x1]
            KernelEnabled: Literal[0x2]
            Wow64Container: Literal[0x4]

        @classmethod
        def GetMachineTypeAttributes(cls, machine: _PE_FILE_MACHINE_TYPES) -> tuple[int, int]: ...
        @classmethod
        def IsWow64GuestMachineSupported(cls, machine: _PE_FILE_MACHINE_TYPES) -> tuple[int, bool]: ...
        @classmethod
        def IsWow64Process2(cls, current_process: int) -> tuple[int, int, int]: ...

    def IsArchExecutable(arch: NormalizedArch) -> bool: ...

def GetNativeArch() -> str: ...

Architecture: NormalizedArch
SubArch: Literal['', 'arm']

def WaitForProcess(process: Popen[str]) -> int: ...
def SanitizeEnv(env: _Environ) -> _Environ: ...
def NeedsSanitizing(env: _Environ) -> bool: ...
def CreateProcess(argv: list[str], executable: str | None = None, env: _Environ | None = None, no_raise: bool = True) -> Popen[str] | None: ...
def MakePath(*list: str) -> str: ...
def RemoveFolderAndContents(path: str) -> None: ...

class FolderChanger:
    old: str
    new: str
    def __init__(self, folder: str) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None) -> None: ...

class Guard:
    obj: Incomplete
    def __init__(self, obj: Incomplete) -> None: ...
    def __enter__(self) -> Incomplete: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: TracebackType | None) -> None: ...

def Execute(argv: Sequence[str], shell: bool = ..., env: Mapping[str, str] | None = ...) -> tuple[Popen[bytes], str, str]: ...
def typeof[T](x: T) -> type[T]: ...

BlobType: type[bytes]

def Unpickle(blob: bytes) -> Any: ...

PICKLE_PROTOCOL: Final[int] = ...

def DiskPickle(obj: dict[str, Any], fp: BinaryIO) -> None: ...
def CompatPickle(obj: Any) -> bytes: ...
def str2b(s: str) -> bytes: ...

sReadIncludes: Final = 0
sLookForIncludeGuard: Final = 1
sFoundIncludeGuard: Final = 2
sIgnoring: Final = 3

def ParseGCCDeps(text: str) -> tuple[str | Any, set[Any]]: ...
def ParseMSVCDeps(out: str, inclusion_pattern: re.Pattern[str] | None = ...) -> tuple[str | Literal[''], list[str]]: ...
def ParseFXCDeps(out: str) -> tuple[str | Literal[''], list[str]]: ...
def ParseSunDeps(text: str) -> tuple[str, set[str]]: ...
def symlink(target: str, link: str) -> tuple[int, str, str]: ...
def DetectSymlinkSupport() -> bool: ...

type _ConsolePrintArgFn = Callable[[TextIO], int | None]

ConsoleGreen: _ConsolePrintArgFn = ...
ConsoleRed: _ConsolePrintArgFn = ...
ConsoleNormal: _ConsolePrintArgFn = ...
ConsoleBlue: _ConsolePrintArgFn = ...
ConsoleHeader: _ConsolePrintArgFn = ...

if sys.platform == 'win32':
    def SwitchColor(fp: TextIO, color: int) -> None: ...

def IsColor(text: _ConsolePrintArgFn | str) -> TypeIs[_ConsolePrintArgFn]: ...

sConsoleColorsEnabled: bool = ...

def DisableConsoleColors() -> None: ...
def con_print(fp: TextIO, args: _ConsolePrintArgFn | str) -> None: ...
def con_print_simple(fp: TextIO, args: str) -> None: ...
def con_out(*args: _ConsolePrintArgFn | str) -> None: ...
def con_err(*args: _ConsolePrintArgFn | str) -> None: ...

LambdaType: type

def IsLambda(v: object) -> bool: ...
def StringType() -> type[str]: ...
def IsString(v: Entry | str | vs.FolderNode) -> TypeIs[str]: ...

class Expando: ...

def rm_path(path: str) -> None: ...
def DecodeConsoleText(origin: TextIO, text: bytes) -> str: ...
def WriteEncodedText(fd: TextIO, text: str) -> None: ...

class CmpOrderable:
    def __init__(self) -> None: ...
    def __lt__(self, other: CmpOrderable) -> bool: ...
    def __le__(self, other: CmpOrderable) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: CmpOrderable) -> bool: ...
    def __ge__(self, other: CmpOrderable) -> bool: ...

class Orderable(CmpOrderable): ...

def compare[T](a: T, b: T) -> int: ...
def RelPathIfCommon(search_path: str, prefix_path: str) -> None: ...
def BuildEnv(cmds: tuple[tuple[str, ...], ...], env: _Environ | None = ...) -> _Environ: ...
def BuildTupleFromDict[KT, VT](obj: Mapping[KT, VT]) -> tuple[tuple[KT, VT], ...]: ...
def BuildDictFromTuple[KT, VT](tup: tuple[tuple[KT, VT], ...]) -> dict[KT, VT]: ...
def MakeLexicalFilename(file: str) -> str: ...
