#!/usr/bin/env python2
# vim: set sts=2 ts=8 sw=2 tw=99 et:
import os, sys
from ambuild2 import run
from optparse import OptionParser

def main():
  options, argv = run.BuildOptions()

  if not len(argv):
    folder = '.'
  else:
    folder = argv[0]
    if not os.path.exists(folder):
      sys.stderr.write('Error: path does not exist: {0}\n'.format(folder))
      sys.exit(1)

  cache_path = os.path.join(folder, '.ambuild2', 'graph')
  if not os.path.exists(cache_path):
    sys.stderr.write('Error: folder was not configured for AMBuild.\n')
    sys.exit(1)

  if not run.Build(os.path.abspath(folder), options, argv):
    sys.exit(1)

if __name__ == '__main__':
  main()

